### ISSUE TITLE
Adding possibility for Desktop mode

### ISSUE THREAD

**Issue by Anixx** [T800G/FolderOptionsX#1]
Hello!

We have discovered that there is a possibility for "Desktop mode" in the FFLAGS pattern. For instance, this FFLAGS option 43000024 makes the folder content appear in "Desktop mode". 

In Desktop Mode it is possible to make icons to have 32px (and smaller) size while having labels below, as on the desktop.

It would be great if you added "Desktop Mode" option to Folder Options X.

Anyway, thank you for this wonderful utility!

**Comment by T800G** [comment]
Project uses only officially documented features.
